import {
  Folder,
  FileText,
  Lightbulb,
  Target,
  BarChart3,
  FlaskConical,
  Briefcase,
  GraduationCap,
  Home,
  Music,
  Palette,
  Camera,
  Wrench,
  Zap,
  Star,
  MessageCircle,
  Calendar,
  Tag,
  Heart,
  Flame,
  Brain,
  BookOpen,
  Mic,
  Laptop,
  Globe,
  Rocket,
  Phone,
  Lock,
  Wallet,
  Gamepad2,
  Dumbbell,
  Plane,
  ShoppingCart,
  Package,
  Clapperboard,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const ICON_OPTIONS: { name: string; icon: LucideIcon }[] = [
  { name: "folder", icon: Folder },
  { name: "file-text", icon: FileText },
  { name: "lightbulb", icon: Lightbulb },
  { name: "target", icon: Target },
  { name: "bar-chart-3", icon: BarChart3 },
  { name: "flask-conical", icon: FlaskConical },
  { name: "briefcase", icon: Briefcase },
  { name: "graduation-cap", icon: GraduationCap },
  { name: "home", icon: Home },
  { name: "music", icon: Music },
  { name: "palette", icon: Palette },
  { name: "camera", icon: Camera },
  { name: "wrench", icon: Wrench },
  { name: "zap", icon: Zap },
  { name: "star", icon: Star },
  { name: "message-circle", icon: MessageCircle },
  { name: "calendar", icon: Calendar },
  { name: "tag", icon: Tag },
  { name: "heart", icon: Heart },
  { name: "flame", icon: Flame },
  { name: "brain", icon: Brain },
  { name: "book-open", icon: BookOpen },
  { name: "mic", icon: Mic },
  { name: "laptop", icon: Laptop },
  { name: "globe", icon: Globe },
  { name: "rocket", icon: Rocket },
  { name: "phone", icon: Phone },
  { name: "lock", icon: Lock },
  { name: "wallet", icon: Wallet },
  { name: "gamepad-2", icon: Gamepad2 },
  { name: "dumbbell", icon: Dumbbell },
  { name: "plane", icon: Plane },
  { name: "shopping-cart", icon: ShoppingCart },
  { name: "package", icon: Package },
  { name: "clapperboard", icon: Clapperboard },
];

export const ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(
  ICON_OPTIONS.map((o) => [o.name, o.icon]),
);

export const COLOR_OPTIONS = [
  null,
  "#C75443",
  "#D97744",
  "#C89B3C",
  "#6B8E3D",
  "#3E8B89",
  "#4A73B8",
  "#6560C4",
  "#8B5AA8",
  "#B85D7D",
  "#7A7670",
];
