// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async healthCheck() : Promise<HealthStatus> {
    return await TAURI_INVOKE("health_check");
},
async listAudioDevices() : Promise<Result<AudioDeviceInfoDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_audio_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultInputDevice() : Promise<Result<AudioDeviceInfoDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_input_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startCapture(micDeviceId: string | null, captureSource: CaptureSourceDto, captureHistorySeconds: number | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_capture", { micDeviceId, captureSource, captureHistorySeconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopCapture() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_capture") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCaptureStatus() : Promise<Result<CaptureStatusDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_capture_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkSystemAudioPermission() : Promise<Result<PermissionStatusDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_system_audio_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async snapshotMicAudio(durationSeconds: number | null) : Promise<Result<AudioSnapshotDto | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("snapshot_mic_audio", { durationSeconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async snapshotSystemAudio(durationSeconds: number | null) : Promise<Result<AudioSnapshotDto | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("snapshot_system_audio", { durationSeconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBufferInfo() : Promise<Result<BufferStatusDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_buffer_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async peekCaptureEnergy(windowSecs: number) : Promise<Result<CaptureEnergyDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("peek_capture_energy", { windowSecs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async triggerInstantCapture(seconds: number, source: CaptureSourceDto, mixConfig: MixConfigDto | null) : Promise<Result<CaptureResultDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trigger_instant_capture", { seconds, source, mixConfig }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startSession() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async endSession(source: CaptureSourceDto, mixConfig: MixConfigDto | null) : Promise<Result<CaptureResultDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("end_session", { source, mixConfig }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSessionStatus() : Promise<Result<SessionStatusDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportSessionWav(sessionId: string, source: CaptureSourceDto, durationSeconds: number, mixConfig: MixConfigDto | null, audioSaveLocation: string | null, audioExportFormat: string | null, mp3Bitrate: number | null) : Promise<Result<SessionWavResultDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_session_wav", { sessionId, source, durationSeconds, mixConfig, audioSaveLocation, audioExportFormat, mp3Bitrate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSessionWav(sessionId: string, audioSaveLocation: string | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_session_wav", { sessionId, audioSaveLocation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableModels() : Promise<Result<ModelInfoDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadModel(size: ModelSizeDto) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { size }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModel(size: ModelSizeDto) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { size }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transcribeAudio(audioPath: string, language: string | null, initialPrompt: string | null) : Promise<Result<TranscriptionResultDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_audio", { audioPath, language, initialPrompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async initWhisperClient(size: ModelSizeDto) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("init_whisper_client", { size }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Engine-aware client init. For `Whisper`, `whisper_model` is required.
 * For `Parakeet`, `parakeet_variant` is required and `enable_diarization`
 * optionally wires Sortformer (auto-downloads if missing). On Apple targets
 * the Parakeet path uses CoreML by default with a per-app persistent cache
 * at `$APP_DATA_DIR/cache/coreml/` so model loads after the first one are
 * sub-second.
 */
async initTranscriptionClient(engine: EngineKindDto, whisperModel: ModelSizeDto | null, parakeetVariant: ParakeetVariantDto | null, enableDiarization: boolean) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("init_transcription_client", { engine, whisperModel, parakeetVariant, enableDiarization }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async shutdownWhisperClient() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("shutdown_whisper_client") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reports whether the Whisper sidecar has been initialized.
 * 
 * The frontend uses this on mount to decide whether to call `init_whisper_client`
 * again. Without it, a Vite HMR remount re-runs autoSetup and respawns the sidecar
 * even when the backend is already warm, leaving `enginePhase: "initializing"`
 * long enough for dictation to fail the readiness check.
 */
async getWhisperStatus() : Promise<Result<WhisperStatusDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_whisper_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the static engine catalogue (Whisper + Parakeet capability + language lists).
 * The frontend uses this to drive the cascading engine → model → language UI.
 */
async getEngineCatalogue() : Promise<Result<EngineDescriptorDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_engine_catalogue") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getParakeetModels() : Promise<Result<ParakeetModelInfoDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_parakeet_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadParakeetModel(variant: ParakeetVariantDto) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_parakeet_model", { variant }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteParakeetModel(variant: ParakeetVariantDto) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_parakeet_model", { variant }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSortformerStatus() : Promise<Result<SortformerModelInfoDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sortformer_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadSortformerModel(variant: SortformerVariantDto) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_sortformer_model", { variant }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSortformerModel(variant: SortformerVariantDto) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_sortformer_model", { variant }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startLiveTranscription(config: LiveTranscriptionConfig) : Promise<Result<LiveTranscriptionStartResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_live_transcription", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopLiveTranscription() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_live_transcription") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLiveTranscriptionStatus() : Promise<Result<LiveTranscriptionStatus, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_live_transcription_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clipboardPaste(text: string, autoPaste: boolean) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clipboard_paste", { text, autoPaste }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAutostartEnabled() : Promise<Result<boolean, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_autostart_enabled") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAutostartEnabled(enabled: boolean) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_autostart_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showOverlayPanel(label: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_overlay_panel", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideOverlayPanel(label: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_overlay_panel", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AudioDeviceInfoDto = { id: string | null; name: string; device_type: DeviceTypeDto; is_default: boolean }
export type AudioSnapshotDto = { samples: number[]; sample_rate: number; channels: number; duration_seconds: number }
export type BufferStatusDto = { mic: RingBufferInfoDto | null; system: RingBufferInfoDto | null }
export type CaptureEnergyDto = { mic_rms: number | null; system_rms: number | null }
export type CaptureResultDto = { file_path: string; duration_seconds: number; sample_rate: number; source: CaptureSourceDtoSerialize }
export type CaptureSourceDto = "MicOnly" | "SystemOnly" | "Mixed"
export type CaptureSourceDtoSerialize = "MicOnly" | "SystemOnly" | "Mixed"
export type CaptureStateDto = "Idle" | "Capturing" | "Error"
export type CaptureStatusDto = { state: CaptureStateDto; mic_active: boolean; system_audio_active: boolean; error_message: string | null }
/**
 * Unified error type for all Tauri commands.
 * 
 * Serializes to `{ "kind": "...", "message": "..." }` via `#[serde(tag = "kind")]`.
 * Auto-generated TypeScript types via specta.
 */
export type CommandError = { kind: "Audio"; message: string } | { kind: "Transcription"; message: string } | { kind: "NotInitialized"; message: string } | { kind: "InvalidInput"; message: string } | { kind: "NotFound"; message: string } | { kind: "Internal"; message: string }
export type DeviceTypeDto = "Input" | "Output"
/**
 * Engine capabilities + supported languages for the cascading UI in Settings.
 */
export type EngineDescriptorDto = { kind: EngineKindDto; display_name: string; languages: string[]; supports_diarization: boolean; supports_initial_prompt: boolean }
/**
 * Which transcription engine the frontend has selected.
 */
export type EngineKindDto = "Whisper" | "Parakeet"
export type HealthStatus = { status: string; version: string }
export type LiveTranscriptionConfig = { 
/**
 * RMS energy threshold below which audio is considered silence. Default: 0.01.
 */
silence_threshold: number; 
/**
 * Milliseconds of continuous silence before triggering a chunk. Default: 800.
 */
silence_duration_ms: number; 
/**
 * Force a chunk after this many seconds of continuous speech. Default: 30.
 */
max_chunk_seconds: number; 
/**
 * Seconds of buffer lookback at session start (backfill). Default: 0.
 */
backfill_seconds: number; 
/**
 * Audio source.
 */
source: CaptureSourceDto; 
/**
 * Mix config for Mixed source (kept for backward compat).
 */
mix_config: MixConfigDto | null; 
/**
 * Whisper language.
 */
language: string | null; 
/**
 * Max characters of prior transcript to feed as Whisper prompt context. Default: 350.
 */
prompt_context_chars: number | null; 
/**
 * Seconds of all-source silence before clearing prompt context to prevent
 * hallucination from stale context. Default: 5.0. Set to 0 to disable.
 */
prompt_decay_silence_seconds: number | null; 
/**
 * Session ID for streaming WAV recording. If set, audio is incrementally
 * written to `$APP_DATA_DIR/audio/{session_id}.wav` during the session.
 */
session_id: string | null; 
/**
 * Custom directory for saving WAV files. If None, uses `$APP_DATA_DIR/audio/`.
 */
audio_save_location: string | null; 
/**
 * Audio export format: "wav" or "mp3". Default: "mp3".
 */
audio_export_format: string | null; 
/**
 * MP3 bitrate in kbps (e.g. 64, 128, 192). Only used when format is "mp3".
 */
mp3_bitrate: number | null; 
/**
 * Request speaker diarization on every transcribed chunk. Honored only
 * when the active engine is Parakeet *and* the sidecar was spawned with
 * a Sortformer model path. Whisper sessions ignore this flag.
 */
diarization?: boolean }
export type LiveTranscriptionPhase = "Running" | "Stopped" | "Error"
export type LiveTranscriptionStartResult = { effective_start_epoch_ms: number }
export type LiveTranscriptionStatus = { phase: LiveTranscriptionPhase; chunks_processed: number; total_audio_seconds: number; error_message: string | null; session_id: string | null; effective_start_epoch_ms: number | null }
export type MixConfigDto = { mic_gain: number; system_gain: number; normalize: boolean }
export type ModelInfoDto = { size: ModelSizeDto; downloaded: boolean; path: string | null; display_name: string; approximate_size_bytes: number }
export type ModelSizeDto = "Tiny" | "Base" | "Small" | "Medium"
export type ParakeetModelInfoDto = { variant: ParakeetVariantDto; downloaded: boolean; display_name: string; approximate_size_bytes: number }
export type ParakeetVariantDto = "TdtV3"
export type PermissionStatusDto = "Granted" | "Denied" | "NotDetermined" | "Unavailable"
export type RingBufferInfoDto = { capacity_samples: number; samples_written: number; available_samples: number; capacity_seconds: number; available_seconds: number; sample_rate: number; channels: number }
export type SessionStatusDto = { active: boolean; elapsed_seconds: number | null }
export type SessionWavResultDto = { file_path: string; duration_seconds: number }
export type SortformerModelInfoDto = { variant: SortformerVariantDto; downloaded: boolean; display_name: string; approximate_size_bytes: number }
export type SortformerVariantDto = "V2_1"
export type TranscriptSegmentDto = { start_ms: number; end_ms: number; text: string; confidence: number; 
/**
 * Populated when the active engine is Parakeet *and* diarization
 * was requested for the originating transcribe call. `None` for Whisper.
 */
speaker_id: number | null }
export type TranscriptionResultDto = { text: string; segments: TranscriptSegmentDto[]; duration_ms: number }
export type WhisperStatusDto = { initialized: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
