// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async healthCheck() : Promise<HealthStatus> {
    return await TAURI_INVOKE("health_check");
},
async listAudioDevices() : Promise<Result<AudioDeviceInfoDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_audio_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultInputDevice() : Promise<Result<AudioDeviceInfoDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_input_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startCapture(micDeviceId: string | null, captureSource: CaptureSourceDto, captureHistorySeconds: number | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_capture", { micDeviceId, captureSource, captureHistorySeconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopCapture() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_capture") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCaptureStatus() : Promise<Result<CaptureStatusDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_capture_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkSystemAudioPermission() : Promise<Result<PermissionStatusDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_system_audio_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBufferInfo() : Promise<Result<BufferStatusDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_buffer_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async peekCaptureEnergy(windowSecs: number) : Promise<Result<CaptureEnergyDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("peek_capture_energy", { windowSecs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSessionWav(sessionId: string, audioSaveLocation: string | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_session_wav", { sessionId, audioSaveLocation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes the listed absolute audio file paths after verifying each lives
 * in a directory the trusted-audio-dirs set knows about. Used by
 * `appStore.deleteSession` to clean up a session's parts — parts may live
 * in directories across the session's lifetime if the user changed
 * `audioSaveLocation` between recording runs, and every directory we've
 * ever written a part to is in the set.
 * 
 * Returns `Err(CommandError)` if any path could not be deleted, listing
 * every failed path so the caller can log/toast a useful diagnostic.
 */
async deleteAudioFiles(paths: string[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_audio_files", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableModels() : Promise<Result<ModelInfoDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadModel(size: ModelSizeDto) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { size }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModel(size: ModelSizeDto) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { size }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transcribeAudio(audioPath: string, language: string | null, initialPrompt: string | null) : Promise<Result<TranscriptionResultDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_audio", { audioPath, language, initialPrompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spawn the sidecar with the requested engine. Whisper requires
 * `whisper_model`; Parakeet requires `parakeet_variant` and may optionally
 * enable Sortformer diarization.
 */
async initTranscriptionClient(engine: EngineKindDto, whisperModel: ModelSizeDto | null, parakeetVariant: ParakeetVariantDto | null, enableDiarization: boolean) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("init_transcription_client", { engine, whisperModel, parakeetVariant, enableDiarization }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async shutdownTranscriptionClient() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("shutdown_transcription_client") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reports whether the transcription sidecar has been initialized.
 * 
 * The frontend uses this on mount to decide whether to call
 * `init_transcription_client` again. Without it, a Vite HMR remount re-runs
 * autoSetup and respawns the sidecar even when the backend is already warm,
 * leaving `enginePhase: "initializing"` long enough for dictation to fail
 * the readiness check.
 */
async getTranscriptionStatus() : Promise<Result<TranscriptionStatusDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcription_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the static engine catalogue (Whisper + Parakeet capability + language lists).
 * The frontend uses this to drive the cascading engine → model → language UI.
 */
async getEngineCatalogue() : Promise<Result<EngineDescriptorDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_engine_catalogue") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getParakeetModels() : Promise<Result<ParakeetModelInfoDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_parakeet_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadParakeetModel(variant: ParakeetVariantDto) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_parakeet_model", { variant }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteParakeetModel(variant: ParakeetVariantDto) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_parakeet_model", { variant }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSortformerStatus() : Promise<Result<SortformerModelInfoDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sortformer_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadSortformerModel(variant: SortformerVariantDto) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_sortformer_model", { variant }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSortformerModel(variant: SortformerVariantDto) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_sortformer_model", { variant }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startLiveTranscription(config: LiveTranscriptionConfig) : Promise<Result<LiveTranscriptionStartResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_live_transcription", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopLiveTranscription() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_live_transcription") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLiveTranscriptionStatus() : Promise<Result<LiveTranscriptionStatus, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_live_transcription_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateVocabularyHints(hints: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_vocabulary_hints", { hints }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clipboardPaste(text: string, autoPaste: boolean) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clipboard_paste", { text, autoPaste }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkScreenCapturePermission() : Promise<Result<ScreenCapturePermissionDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_screen_capture_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Triggers the Screen Recording TCC prompt if the app has never asked. The
 * OS dialog is shown asynchronously, so callers should re-check via
 * `check_screen_capture_permission` after the user has responded.
 */
async requestScreenCapturePermission() : Promise<Result<ScreenCapturePermissionDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_screen_capture_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAutostartEnabled() : Promise<Result<boolean, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_autostart_enabled") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAutostartEnabled(enabled: boolean) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_autostart_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showOverlayPanel(label: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_overlay_panel", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideOverlayPanel(label: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_overlay_panel", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Snapshot of recent entries from the in-memory ring buffer.
 * `limit` caps the number returned (default 500 = the full buffer).
 */
async getRecentLogs(limit: number | null) : Promise<Result<LogEntry[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recent_logs", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear the in-memory ring buffer. Does not touch on-disk log files.
 */
async clearLogs() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_logs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the resolved log directory path as a string, for display in the UI.
 */
async getLogDir() : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open Finder / Explorer to the log directory so the user can grab the files
 * to send to support.
 */
async revealLogDir() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AudioDeviceInfoDto = { id: string | null; name: string; device_type: DeviceTypeDto; is_default: boolean }
export type BufferStatusDto = { mic: RingBufferInfoDto | null; system: RingBufferInfoDto | null }
export type CaptureEnergyDto = { mic_rms: number | null; system_rms: number | null }
export type CaptureSourceDto = "MicOnly" | "SystemOnly" | "Mixed"
export type CaptureStateDto = "Idle" | "Capturing" | "Error"
export type CaptureStatusDto = { state: CaptureStateDto; mic_active: boolean; system_audio_active: boolean; error_message: string | null }
/**
 * Unified error type for all Tauri commands.
 * 
 * Serializes to `{ "kind": "...", "message": "..." }` via `#[serde(tag = "kind")]`.
 * Auto-generated TypeScript types via specta.
 */
export type CommandError = { kind: "Audio"; message: string } | { kind: "Transcription"; message: string } | { kind: "NotInitialized"; message: string } | { kind: "InvalidInput"; message: string } | { kind: "NotFound"; message: string } | { kind: "Internal"; message: string }
export type DeviceTypeDto = "Input" | "Output"
/**
 * Engine capabilities + supported languages for the cascading UI in Settings.
 */
export type EngineDescriptorDto = { kind: EngineKindDto; display_name: string; languages: string[]; supports_diarization: boolean; supports_initial_prompt: boolean }
/**
 * Which transcription engine the frontend has selected.
 */
export type EngineKindDto = "Whisper" | "Parakeet"
export type HealthStatus = { status: string; version: string }
export type LiveTranscriptionConfig = { 
/**
 * Milliseconds of continuous silence before triggering a chunk. Default: 800.
 */
silence_duration_ms: number; 
/**
 * Force a chunk after this many seconds of continuous speech. Default: 30.
 */
max_chunk_seconds: number; 
/**
 * Seconds of buffer lookback at session start (backfill). Default: 0.
 */
backfill_seconds: number; 
/**
 * Audio source.
 */
source: CaptureSourceDto; 
/**
 * Mix config for Mixed source (kept for backward compat).
 */
mix_config: MixConfigDto | null; 
/**
 * Whisper language.
 */
language: string | null; 
/**
 * Max characters of prior transcript to feed as Whisper prompt context. Default: 350.
 */
prompt_context_chars: number | null; 
/**
 * Seconds of all-source silence before clearing prompt context to prevent
 * hallucination from stale context. Default: 5.0. Set to 0 to disable.
 */
prompt_decay_silence_seconds: number | null; 
/**
 * Session ID for streaming session-audio recording. If set, the loop
 * streams a new **session audio part** to disk during the session and
 * inserts a `session_audio_parts` row at finalize time before emitting
 * `session-part-ready`. The on-disk file is
 * `{audio_save_location || $APP_DATA_DIR/audio/}/{session_id}.{part_index}.{wav|mp3}`,
 * where `part_index` is 0 for a fresh session and `N` when resuming a
 * session that already has parts.
 */
session_id: string | null; 
/**
 * Custom directory for saving session audio parts. If None, uses
 * `$APP_DATA_DIR/audio/`. The directory is registered with
 * `audio_save_locations` at recording start so reconciliation can
 * recover orphan parts on the next startup.
 */
audio_save_location: string | null; 
/**
 * Audio export format applied at part finalization: "wav" or "mp3".
 * Default: "mp3". Choosing "mp3" re-encodes the streamed WAV at
 * `mp3_bitrate` and deletes the source WAV; "wav" keeps the streamed
 * file as-is.
 */
audio_export_format: string | null; 
/**
 * MP3 bitrate in kbps (e.g. 64, 128, 192). Only used when format is "mp3".
 */
mp3_bitrate: number | null; 
/**
 * Request speaker diarization on every transcribed chunk. Honored only
 * when the active engine is Parakeet *and* the sidecar was spawned with
 * a Sortformer model path. Whisper sessions ignore this flag.
 */
diarization?: boolean; 
/**
 * Comma-separated vocabulary hints (folder/tag names) prepended to the
 * Whisper initial_prompt to improve recognition of proper nouns. Ignored
 * for Parakeet sessions (the TDT decoder has no text-prompt input).
 */
vocabulary_hints: string | null; 
/**
 * When set, this run is a resume of an existing Session. The new
 * recording becomes a fresh audio part appended after the existing parts;
 * no prior file is read or modified. Backfill is forced to 0.
 */
resume?: ResumeConfig | null }
export type LiveTranscriptionPhase = "Running" | "Stopped" | "Error"
export type LiveTranscriptionStartResult = { effective_start_epoch_ms: number }
export type LiveTranscriptionStatus = { phase: LiveTranscriptionPhase; chunks_processed: number; total_audio_seconds: number; error_message: string | null; session_id: string | null; effective_start_epoch_ms: number | null }
/**
 * One log line visible to the frontend. `ts_ms` is unix-epoch milliseconds.
 */
export type LogEntry = { ts_ms: number; level: LogLevel; target: string; message: string }
/**
 * Mirrors the five `tracing::Level` values so the frontend gets a
 * typed union instead of an unchecked string.
 */
export type LogLevel = "ERROR" | "WARN" | "INFO" | "DEBUG" | "TRACE"
export type MixConfigDto = { mic_gain: number; system_gain: number; normalize: boolean }
export type ModelInfoDto = { size: ModelSizeDto; downloaded: boolean; path: string | null; display_name: string; approximate_size_bytes: number }
export type ModelSizeDto = "Tiny" | "Base" | "Small" | "Medium"
export type ParakeetModelInfoDto = { variant: ParakeetVariantDto; downloaded: boolean; display_name: string; approximate_size_bytes: number }
export type ParakeetVariantDto = "TdtV3"
export type PermissionStatusDto = "Granted" | "Denied" | "NotDetermined" | "Unavailable"
export type ResumeConfig = { 
/**
 * The index of the new part being recorded — equals the count of
 * existing parts in the session. The output WAV/MP3 is named
 * `{session_id}.{part_index}.{ext}`.
 */
part_index: number; 
/**
 * Cumulative duration of the existing parts. Added to every Segment's
 * `audio_offset_seconds` so persisted Segments stay continuous.
 */
offset_base_seconds: number }
export type RingBufferInfoDto = { capacity_samples: number; samples_written: number; available_samples: number; capacity_seconds: number; available_seconds: number; sample_rate: number; channels: number }
export type ScreenCapturePermissionDto = "Granted" | "NotDetermined" | "Unavailable"
export type SortformerModelInfoDto = { variant: SortformerVariantDto; downloaded: boolean; display_name: string; approximate_size_bytes: number }
export type SortformerVariantDto = "V2_1"
export type TranscriptSegmentDto = { start_ms: number; end_ms: number; text: string; confidence: number; 
/**
 * Populated when the active engine is Parakeet *and* diarization
 * was requested for the originating transcribe call. `None` for Whisper.
 */
speaker_id: number | null }
export type TranscriptionResultDto = { text: string; segments: TranscriptSegmentDto[]; duration_ms: number }
export type TranscriptionStatusDto = { initialized: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
